version: '3.8'

services:

  postgres:
    container_name: postgres-test-service
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: test_service_db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    container_name: redis-test-service
    image: redis:6.2-alpine
    ports:
      - "6380:6379"
    command: redis-server --save 60 1 --appendonly yes --appendfsync everysec>
    environment:
      REDIS_PASSWORD: qwerty456
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  pgdata:
  redis-volume: