server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: public

  datasource:
    url: jdbc:postgresql://localhost:5433/test_service_db
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${spring.datasource.url}
      maximum-pool-size: 40
      username: postgres
      password: qwerty123

  data:
    redis:
      host: localhost
      port: 6380
      password: qwerty456
  sql:
    init:
      mode: embedded

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
    access-expired: 1800000
    refresh-expired: 3600000